# Collaborative Filtering

It has two parts:
1. User-based collaborative filtering:
    <p>
        These system recommend movies to a user that a similar user has liked. The measure of similarity is based on the ratings given by the user. The similarity is calculated using the cosine similarity, or the Pearson correlation coefficient. 
    </p>
2. Item-based collaborative filtering:
    <p>
        These system recommend movies to a user that are similar to the movies that the user has liked. The measure of similarity is based on the ratings given by the user. The similarity is calculated using the cosine similarity, or the Pearson correlation coefficient.
    </p>

In [1]:
# ! pip install surprise

Collecting surprise
  Downloading surprise-0.1-py2.py3-none-any.whl (1.8 kB)
Collecting scikit-surprise
  Downloading scikit-surprise-1.1.3.tar.gz (771 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 772.0/772.0 kB 550.3 kB/s eta 0:00:0000:0100:01
  Preparing metadata (setup.py) ... done
Requirement already satisfied: joblib>=1.0.0 in /home/darklord/anaconda3/lib/python3.9/site-packages (from scikit-surprise->surprise) (1.1.1)
Requirement already satisfied: numpy>=1.17.3 in /home/darklord/anaconda3/lib/python3.9/site-packages (from scikit-surprise->surprise) (1.21.5)
Requirement already satisfied: scipy>=1.3.2 in /home/darklord/anaconda3/lib/python3.9/site-packages (from scikit-surprise->surprise) (1.7.3)
Building wheels for collected packages: scikit-surprise
  Building wheel for scikit-surprise (setup.py) ... done
  Created wheel for scikit-surprise: filename=scikit_surprise-1.1.3-cp39-cp39-linux_x86_64.whl size=1202911 sha256=721ab1a9ca6a1450ac2ab509b079298ab87c790adc29e6336cb697972a5a8756
  Stored in directory: /home/darklord/.cache/pip/wheels/c6/3a/46/9b17b3512bdf283c6cb84f59929cdd5199d4e754d596d22784
Successfully built scikit-surprise
Installing collected packages: scikit-surprise, surprise
Successfully installed scikit-surprise-1.1.3 surprise-0.1

In [5]:
import pandas as pd
import numpy as np
from surprise import Reader, Dataset, SVD
from surprise.model_selection import cross_validate

In [6]:
df=pd.read_csv('./ratings_small.csv')
reader=Reader()
df.head()

   userId  movieId  rating   timestamp
0       1       31     2.5  1260759144
1       1     1029     3.0  1260759179
2       1     1061     3.0  1260759182
3       1     1129     2.0  1260759185
4       1     1172     4.0  1260759205

In [9]:
data=Dataset.load_from_df(df[['userId','movieId','rating']],reader)

In [10]:
svd=SVD()
cross_validate(svd,data,measures=['RMSE','MAE'],cv=5,verbose=True)

Evaluating RMSE, MAE of algorithm SVD on 5 split(s).

                  Fold 1  Fold 2  Fold 3  Fold 4  Fold 5  Mean    Std
RMSE (testset)    0.8971  0.9030  0.8904  0.8903  0.9027  0.8967  0.0056
MAE (testset)     0.6903  0.6961  0.6848  0.6864  0.6930  0.6901  0.0042
Fit time          1.04    1.06    0.94    0.95    1.01    1.00    0.05
Test time         0.11    0.10    0.10    0.10    0.11    0.10    0.01

{'test_rmse': array([0.8971033 , 0.90303663, 0.89035208, 0.89028362, 0.90272819]),
 'test_mae': array([0.69033863, 0.69610863, 0.68479794, 0.68638858, 0.69300317]),
 'fit_time': (1.0420305728912354,
  1.0562963485717773,
  0.94338059425354,
  0.9520645141601562,
  1.0069353580474854),
 'test_time': (0.10947179794311523,
  0.09787511825561523,
  0.09540867805480957,
  0.09580278396606445,
  0.1067967414855957)}

In [12]:
train=data.build_full_trainset()
svd.fit(train)

In [13]:
df[df['userId']==1]

    userId  movieId  rating   timestamp
0        1       31     2.5  1260759144
1        1     1029     3.0  1260759179
2        1     1061     3.0  1260759182
3        1     1129     2.0  1260759185
4        1     1172     4.0  1260759205
5        1     1263     2.0  1260759151
6        1     1287     2.0  1260759187
7        1     1293     2.0  1260759148
8        1     1339     3.5  1260759125
9        1     1343     2.0  1260759131
10       1     1371     2.5  1260759135
11       1     1405     1.0  1260759203
12       1     1953     4.0  1260759191
13       1     2105     4.0  1260759139
14       1     2150     3.0  1260759194
15       1     2193     2.0  1260759198
16       1     2294     2.0  1260759108
17       1     2455     2.5  1260759113
18       1     2968     1.0  1260759200
19       1     3671     3.0  1260759117

In [14]:
svd.predict(1,302,3)

Prediction(uid=1, iid=302, r_ui=3, est=2.730039104355213, details={'was_impossible': False})