# Moview Recommendation System

**Types  of Rocommendatioin Systems**

Machine Leaninig algorithims in recommender systems typicaaly fit into two categories:
1. Content-based systems
2. collaborative filtering systems

**1. Content-Based Movie Recommendation Systems**
<!-- <img src='test.jpg -->
Content-based methods are based on the similarity of movie attributes.Using this type of recommender system, is a user watches one movie, similar movies are recommended.
Example: if a user watches a moview starring *Tom Cruise* the system will recommenf them movies in the same genre starring *Tom Cruise*.

<img src='./content-based.jpg'>

**2. Collaborative Filtering Movie Recommendation Systems**

With collaborative filteringm the system is based in past intertacions between user and movies. The system will recommend movies that are similar to movies that a user has watched in the past.
Example: if a user **A** watches movie M1, M2 and M3 and user **B** watches M1, M2,M3 and M4, the system will recommend M4 to user **C**.

In [1]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
%matplotlib inline
credits=pd.read_csv('./10000 Credits Data')
movies=pd.read_csv('./10000 Movies Data')

In [2]:
credits

,Unnamed: 0,Movie_id,title,Cast,Crew
0,0,238,The Godfather,"[{'adult': False, 'gender': 2, 'id': 3084, 'kn...","[{'adult': False, 'gender': 2, 'id': 154, 'kno..."
1,1,278,The Shawshank Redemption,"[{'adult': False, 'gender': 2, 'id': 504, 'kno...","[{'adult': False, 'gender': 2, 'id': 153, 'kno..."
2,2,240,The Godfather Part II,"[{'adult': False, 'gender': 2, 'id': 1158, 'kn...","[{'adult': False, 'gender': 2, 'id': 154, 'kno..."
3,3,19404,Dilwale Dulhania Le Jayenge,"[{'adult': False, 'gender': 2, 'id': 35742, 'k...","[{'adult': False, 'gender': 1, 'id': 8311, 'kn..."
4,4,424,Schindler's List,"[{'adult': False, 'gender': 2, 'id': 3896, 'kn...","[{'adult': False, 'gender': 2, 'id': 491, 'kno..."
...,...,...,...,...,...
9975,9975,384737,Precious Cargo,"[{'adult': False, 'gender': 2, 'id': 62, 'know...","[{'adult': False, 'gender': 2, 'id': 4951, 'kn..."
9976,9976,282813,The Pyramid,"[{'adult': False, 'gender': 1, 'id': 589098, '...","[{'adult': False, 'gender': 2, 'id': 5673, 'kn..."
9977,9977,134375,Home Alone: The Holiday Heist,"[{'adult': False, 'gender': 1, 'id': 8338, 'kn...","[{'adult': False, 'gender': 2, 'id': 11505, 'k..."
9978,9978,10477,Driven,"[{'adult': False, 'gender': 2, 'id': 16483, 'k...","[{'adult': False, 'gender': 1, 'id': 2324, 'kn..."
9979,9979,243688,Poltergeist,"[{'adult': False, 'gender': 2, 'id': 6807, 'kn...","[{'adult': False, 'gender': 0, 'id': 8375, 'kn..."

In [3]:
movies

,Unnamed: 0,Movie_id,title,Genres,release_date,Keywords,overview,poster_path,Budget,Revenue,popularity,vote_average,vote_count
0,0,238,The Godfather,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",1972-03-14,"[{'id': 131, 'name': 'italy'}, {'id': 697, 'na...","Spanning the years 1945 to 1955, a chronicle o...",/3bhkrj58Vtu7enYsRolD1fZdja1.jpg,245066411,245066411,93.552,8.7,16814
1,1,278,The Shawshank Redemption,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",1994-09-23,"[{'id': 378, 'name': 'prison'}, {'id': 417, 'n...",Framed in the 1940s for the double murder of h...,/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg,28341469,28341469,78.664,8.7,22542
2,2,240,The Godfather Part II,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",1974-12-20,"[{'id': 131, 'name': 'italy'}, {'id': 700, 'na...",In the continuing saga of the Corleone crime f...,/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg,102600000,102600000,55.752,8.6,10187
3,3,19404,Dilwale Dulhania Le Jayenge,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",1995-10-19,[],"Raj is a rich, carefree, happy-go-lucky second...",/2CAL2433ZeIihfX1Hb2139CX0pW.jpg,100000000,100000000,22.150,8.6,3927
4,4,424,Schindler's List,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",1993-12-15,"[{'id': 818, 'name': 'based on novel or book'}...",The true story of how businessman Oskar Schind...,/sF1U4EUQS8YHUYjNl3pMGNIQyr0.jpg,321365567,321365567,53.542,8.6,13382
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9975,9975,384737,Precious Cargo,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",2016-07-15,"[{'id': 9730, 'name': 'crime boss'}, {'id': 10...","After a botched heist, Eddie a murderous crim...",/dOQv2PDBu9bBCZRLeRp6QQYJDr3.jpg,100659,100659,14.663,5.2,243
9976,9976,282813,The Pyramid,"[{'id': 27, 'name': 'Horror'}]",2014-12-04,"[{'id': 1299, 'name': 'monster'}, {'id': 3762,...",An archaeological team attempt to unlock the s...,/joPb4PUPP7xClD6XPiQ7laBEtZf.jpg,16861137,16861137,17.892,5.2,861
9977,9977,134375,Home Alone: The Holiday Heist,"[{'id': 35, 'name': 'Comedy'}, {'id': 10751, '...",2012-11-25,"[{'id': 207317, 'name': 'christmas'}]",8-year-old Finn is terrified to learn his fami...,/6JPrRC0JPM06y17pUXD6w1xMvKi.jpg,0,0,23.978,5.2,335
9978,9978,10477,Driven,"[{'id': 28, 'name': 'Action'}]",2001-04-27,"[{'id': 271, 'name': 'competition'}, {'id': 36...",Talented rookie race-car driver Jimmy Bly has ...,/2aN2BBAbRyfEpfxZAQY82T8zWRq.jpg,54744738,54744738,13.200,5.2,594
9979,9979,243688,Poltergeist,"[{'id': 27, 'name': 'Horror'}]",2015-05-20,"[{'id': 3350, 'name': 'poltergeist'}, {'id': 3...",A family's suburban home is invaded by angry s...,/A1ymtbzatZp94Z49ZOBb8JGXOBB.jpg,95437994,95437994,42.458,5.2,2037